# Generated by Django 5.1.2 on 2025-01-23 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='Customer_email',
            new_name='customer_email',
        ),
    ]
